<?php
require_once __DIR__.'/bakery_auth.php';
$bakeryDb=bakeryDbOrFail();$bakeryAccount=requireBakerySession($bakeryDb);
$range=bakeryMonthRange($_GET);
$stmt=$bakeryDb->prepare("SELECT COALESCE(SUM(amount),0) total FROM bakery_investments WHERE status='paid' AND investment_date BETWEEN ? AND ?");$stmt->bind_param('ss',$range['from_date'],$range['to_date']);$stmt->execute();$investment=(float)$stmt->get_result()->fetch_assoc()['total'];
$stmt=$bakeryDb->prepare("SELECT COALESCE(SUM(total_amount),0) total FROM bakery_equipment WHERE status<>'planned' AND purchase_date BETWEEN ? AND ?");$stmt->bind_param('ss',$range['from_date'],$range['to_date']);$stmt->execute();$equipment=(float)$stmt->get_result()->fetch_assoc()['total'];
$stmt=$bakeryDb->prepare("SELECT COALESCE(SUM(quantity*unit_cost),0) total FROM bakery_stock_movements WHERE movement_type='purchase' AND movement_date BETWEEN ? AND ?");$stmt->bind_param('ss',$range['from_date'],$range['to_date']);$stmt->execute();$materials=(float)$stmt->get_result()->fetch_assoc()['total'];
$stmt=$bakeryDb->prepare("SELECT COALESCE(SUM(amount),0) total FROM bakery_operating_expenses WHERE status='paid' AND expense_date BETWEEN ? AND ?");$stmt->bind_param('ss',$range['from_date'],$range['to_date']);$stmt->execute();$operating=(float)$stmt->get_result()->fetch_assoc()['total'];
$overall=$investment+$equipment+$materials+$operating;
$stock=$bakeryDb->query("SELECT m.id,m.name,m.unit,m.minimum_stock,COALESCE(s.stock,0) AS stock FROM bakery_materials m LEFT JOIN (SELECT material_id,SUM(CASE WHEN movement_type IN ('purchase','adjustment_in') THEN quantity ELSE -quantity END) AS stock FROM bakery_stock_movements GROUP BY material_id) s ON s.material_id=m.id WHERE m.is_active=1 ORDER BY (COALESCE(s.stock,0)<=m.minimum_stock) DESC,m.name")->fetch_all(MYSQLI_ASSOC);
$low=array_values(array_filter($stock,function($row){return (float)$row['stock']<=(float)$row['minimum_stock'];}));
$stmt=$bakeryDb->prepare("SELECT s.movement_date,s.movement_type,s.quantity,s.unit_cost,s.supplier,m.name,m.unit FROM bakery_stock_movements s JOIN bakery_materials m ON m.id=s.material_id WHERE s.movement_date BETWEEN ? AND ? ORDER BY s.movement_date DESC,s.id DESC LIMIT 12");$stmt->bind_param('ss',$range['from_date'],$range['to_date']);$stmt->execute();$recent=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$movementLabels=['purchase'=>'Mua vào','usage'=>'Sử dụng','adjustment_in'=>'Nhập điều chỉnh','adjustment_out'=>'Xuất điều chỉnh'];
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/svg+xml" href="bakery_favicon.svg"><title>Tổng quan bếp bánh</title></head><body><?php require __DIR__.'/bakery_nav.php';?><main class="bk-shell"><header class="bk-header"><div><h1>Tổng quan bếp bánh</h1><p>Toàn bộ đầu tư, thiết bị, nguyên vật liệu và tồn kho trong một hệ thống riêng.</p></div></header>
<form class="bk-filter bk-filter-card"><div><label class="bk-label">Từ tháng</label><input class="bk-input" type="month" name="from_month" value="<?=bakeryH($range['from_month'])?>"></div><div><label class="bk-label">Đến tháng</label><input class="bk-input" type="month" name="to_month" value="<?=bakeryH($range['to_month'])?>"></div><button class="bk-btn bk-btn-secondary">Xem báo cáo</button></form>
<section class="bk-stats"><div class="bk-stat orange"><span>Tổng chi phí trong khoảng</span><strong><?=bakeryMoney($overall)?></strong><small>Đầu tư + thiết bị + vận hành + nguyên liệu</small></div><div class="bk-stat orange"><span>Phần thô đã thanh toán</span><strong><?=bakeryMoney($investment)?></strong></div><div class="bk-stat blue"><span>Thiết bị đang triển khai</span><strong><?=bakeryMoney($equipment)?></strong></div><div class="bk-stat orange"><span>Chi phí vận hành</span><strong><?=bakeryMoney($operating)?></strong><small>Đã thanh toán trong khoảng</small></div><div class="bk-stat green"><span>Đã mua nguyên liệu</span><strong><?=bakeryMoney($materials)?></strong></div><div class="bk-stat red"><span>Nguyên liệu cần chú ý</span><strong><?=count($low)?></strong><small>Tồn hiện tại bằng hoặc dưới mức tối thiểu</small></div></section>
<section class="bk-quick"><a href="bakery_investments.php"><strong>🏗️ Đầu tư phần thô</strong><span>Quản lý xây dựng, điện nước và nhà thầu</span></a><a href="bakery_equipment.php"><strong>⚙️ Thiết bị</strong><span>Theo dõi mua sắm và trạng thái lắp đặt</span></a><a href="bakery_operating_expenses.php"><strong>💡 Chi phí vận hành</strong><span>Tiền thuê, điện, nước và chi phí thường xuyên</span></a><a href="bakery_material_purchases.php"><strong>🧺 Mua nguyên liệu</strong><span>Nhập hàng và tự động cộng tồn kho</span></a><a href="bakery_revenue.php"><strong>💰 Doanh thu Bakery</strong><span>Tự động lấy món thuộc danh mục Bakery từ POS</span></a></section>
<div class="bk-grid bk-grid-2" style="margin-top:16px"><section class="bk-card"><h2 class="bk-card-title">Cảnh báo tồn kho</h2><?php if(!$low):?><div class="bk-empty">Không có nguyên liệu dưới mức tối thiểu.</div><?php else:?><div class="bk-table-wrap"><table class="bk-table"><thead><tr><th>Nguyên liệu</th><th>Tồn</th><th>Tối thiểu</th></tr></thead><tbody><?php foreach($low as $row):?><tr><td><strong><?=bakeryH($row['name'])?></strong></td><td class="bk-low"><?=bakeryNumber($row['stock']).' '.bakeryH($row['unit'])?></td><td><?=bakeryNumber($row['minimum_stock']).' '.bakeryH($row['unit'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><section class="bk-card"><h2 class="bk-card-title">Nhập xuất gần đây</h2><?php if(!$recent):?><div class="bk-empty">Chưa có dữ liệu kho.</div><?php else:?><div class="bk-table-wrap"><table class="bk-table"><thead><tr><th>Ngày</th><th>Nguyên liệu</th><th>Loại</th><th>Số lượng</th></tr></thead><tbody><?php foreach($recent as $row):?><tr><td><?=date('d/m/Y',strtotime($row['movement_date']))?></td><td><?=bakeryH($row['name'])?></td><td><?=bakeryH($movementLabels[$row['movement_type']]??$row['movement_type'])?></td><td class="<?=in_array($row['movement_type'],['purchase','adjustment_in'],true)?'bk-ok':'bk-low'?>"><?=in_array($row['movement_type'],['purchase','adjustment_in'],true)?'+':'−'?><?=bakeryNumber($row['quantity']).' '.bakeryH($row['unit'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div></main></body></html>
