<?php
define('GHE_ENGLISH',true);
require_once __DIR__.'/site/bootstrap.php';
$pageKey=$_GET['view']??'home';
if (!is_string($pageKey) || !isset(ghe_english_routes()[$pageKey])) {
    http_response_code(404); header('X-Robots-Tag: noindex'); exit('Page not found.');
}
require __DIR__.'/site/header.php';
?>
<?php if($pageKey==='home'): ?>
<section class="hero wrap">
  <div class="hero-copy"><p class="eyebrow">GHÉ · DA LAT CAFÉ</p><h1><?= nl2br(ghe_h($site['home_title'])) ?></h1><p><?= ghe_h($site['home_intro']) ?></p><p class="opening-hours"><?= ghe_h($site['hours']) ?></p><div class="actions"><a class="button" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>">Explore the menu ↗</a><a class="text-link" href="<?= ghe_h(ghe_link('den-ghe.php')) ?>">Find your way here →</a></div></div>
  <?php if(!empty($content['media'][$site['hero_image']])): ?><div class="hero-photo"><?php ghe_photo($site['hero_image'],'',true); ?></div>
  <?php else: ?><div class="hero-art" aria-hidden="true"><div class="art-note">A MOMENT IN DA LAT.</div><div class="art-word">ghé</div><div class="steam steam-one"></div><div class="steam steam-two"></div><div class="saucer"></div><div class="cup"><div class="coffee-surface"></div><span>ghé</span></div><span class="art-flower">✳</span><div class="art-caption">coffee & good company</div></div><?php endif; ?>
</section>
<div class="ribbon"><div class="wrap"><span><?= ghe_h($site['hours']) ?></span><span aria-hidden="true">✳</span><span><?= ghe_h($site['street']) ?></span></div></div>
<section class="section wrap intro-grid"><p class="eyebrow">01 / MAKE YOURSELF AT HOME</p><div><h2><?= ghe_h($site['about_title']) ?></h2><?php ghe_english_facilities(); ?><a class="text-link" href="<?= ghe_h(ghe_link('gioi-thieu.php')) ?>">A little more about Ghé →</a></div></section>
<?php ghe_gallery(); $featured=ghe_featured_items(); if($featured): ?>
<section class="section menu-preview"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">02 / WHAT ARE YOU HAVING?</p><h2>Your day.<br>Your favourite flavour.</h2></div><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>">Browse the full menu →</a></div><div class="drink-grid">
<?php foreach($featured as $index=>$drink): ?><article class="drink-card"><?php if(!empty($content['media'][$drink['image']])): ghe_photo($drink['image'],'drink-photo'); else: ?><div class="drink-art <?= ['coffee','citrus','matcha'][$index%3] ?>" aria-hidden="true"><span style="font:italic 76px var(--serif);color:var(--coffee)" aria-hidden="true">ghé ✳</span><small>FROM OUR MENU</small></div><?php endif; ?><div class="drink-title"><h3><?= ghe_h($drink['name']) ?></h3><span><?= ghe_price($drink['price']) ?></span></div><p><?= ghe_h($drink['detail']) ?></p></article><?php endforeach; ?>
</div></div></section><?php endif; ?>
<section class="section wrap story-teaser"><div class="editorial-number" aria-hidden="true">ghé<br><em>stay a little.</em></div><div><p class="eyebrow">03 / FIND YOUR FLAVOUR</p><h2>A drink for<br>your kind of day.</h2><p>Start with a familiar favourite or explore something new. Our menu guide makes it easy to find your way around.</p><a class="text-link" href="<?= ghe_h(ghe_link('ghe-uong-gi.php')) ?>">What to order at Ghé →</a></div></section>
<section class="section wrap location-strip"><p class="eyebrow">SAVE A SPOT ON YOUR MAP</p><h2><?= ghe_h($site['address']) ?></h2><p><?= ghe_h($site['hours']) ?></p><a class="button outline" href="<?= ghe_h($site['maps']) ?>" target="_blank" rel="noopener noreferrer">Find Ghé on Google Maps ↗</a></section>
<?php elseif($pageKey==='about'): ?>
<section class="page-intro wrap"><p class="eyebrow">ABOUT GHÉ / DA LAT CAFÉ</p><h1><?= ghe_h($site['about_title']) ?></h1><p class="lead"><?= ghe_h($site['home_intro']) ?></p></section>
<section class="wrap section editorial"><aside class="paper-note"><span class="eyebrow">AN ADDRESS TO REMEMBER</span><h2><?= ghe_h($site['street']) ?></h2><span><?= ghe_h($site['city'].', '.$site['region']) ?></span><p><?= ghe_h($site['hours']) ?></p><a class="text-link" href="<?= ghe_h(ghe_link('den-ghe.php')) ?>">Plan your visit →</a></aside><div class="prose"><?php ghe_paragraphs($site['about_body']); ?><h2>Spaces & facilities</h2><?php ghe_english_facilities(); ?><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>">Explore our menu →</a></div></section>
<?php ghe_gallery(); ?>
<section class="wrap section review-note"><p class="eyebrow">FROM PEOPLE WHO HAVE STOPPED BY</p><h2>See Ghé through our guests’ eyes.</h2><p>Read reviews and browse guest photos on our Google Maps profile for another perspective before your visit.</p><a class="text-link" href="<?= ghe_h($site['maps']) ?>" target="_blank" rel="noopener noreferrer">Read reviews on Google Maps ↗</a></section>
<?php elseif($pageKey==='menu'): ?>
<section class="page-intro wrap"><p class="eyebrow">THE MENU / GHÉ DA LAT</p><h1>Pick a drink.<br><em>Stay for a story.</em></h1><p class="lead"><?= ghe_h($site['menu_intro']) ?></p><p class="fine-print">All prices are in Vietnamese dong (VND). Please confirm prices and availability when ordering. If you have a food allergy or dietary requirement, ask our team about ingredients before ordering.</p></section>
<div class="wrap menu-tools" data-menu-tools hidden><label for="public-menu-search">Find your favourite</label><input id="public-menu-search" type="search" placeholder="Try coffee, matcha, bạc xỉu…" autocomplete="off"><p class="fine-print" id="menu-result" role="status" aria-live="polite"></p></div>
<nav class="wrap category-nav" aria-label="Menu categories"><?php foreach($menuSections as $section): ?><a href="#<?= ghe_h($section['id']) ?>"><?= ghe_h($section['title']) ?></a><?php endforeach; ?></nav>
<div class="wrap menu-list">
<?php if(!$menuSections): ?><p class="empty-results"><?= $catalogAvailable?'Our menu is being updated.':'The menu is temporarily unavailable.' ?> Please call <a href="tel:<?= ghe_h($site['telephone']) ?>"><?= ghe_h($site['phone']) ?></a> to ask about items and prices.</p><?php endif; ?>
<?php foreach($menuSections as $index=>$section): ?><section class="menu-section" id="<?= ghe_h($section['id']) ?>" data-menu-section><div class="menu-section-heading"><p class="eyebrow"><?= sprintf('%02d',$index+1) ?> / ON THE MENU</p><h2><?= ghe_h($section['title']) ?></h2></div><div class="menu-items">
<?php foreach($section['items'] as $item): ?><article class="menu-item" data-menu-item data-search="<?= ghe_h($section['title'].' '.$item['name'].' '.$item['name_vi'].' '.$item['detail']) ?>"><?php if(!empty($content['media'][$item['image']]))ghe_photo($item['image'],'menu-photo'); ?><div class="menu-item-top"><h3><?= ghe_h($item['name']) ?></h3><span><?= ghe_price($item['price']) ?></span></div><p class="menu-original" lang="vi"><?= ghe_h($item['name_vi']) ?></p><p><?= ghe_h($item['detail']) ?></p><?php if($item['tags']): ?><div class="tags"><?php foreach($item['tags'] as $tag): ?><span><?= ghe_h($tag) ?></span><?php endforeach; ?></div><?php endif; ?></article><?php endforeach; ?>
</div></section><?php endforeach; ?>
<p class="empty-results" id="menu-empty" hidden>No matching items. Try a shorter name or clear your search.</p></div>
<?php elseif($pageKey==='story'): ?>
<article><header class="page-intro wrap"><p class="eyebrow">A LITTLE MENU GUIDE</p><h1>One coffee break.<br><em>Plenty of possibilities.</em></h1><p class="lead">A work session, a study break or a catch-up with friends can start with a drink you love. Here is a look at what is currently on the menu.</p></header>
<div class="wrap section prose"><h2>Follow your own taste.</h2><p>Whether you know what you like or want to try something different, check the descriptions and prices below. Ask our team about ingredients and serving options.</p>
<?php foreach($menuSections as $section): ?><section><h2><?= ghe_h($section['title']) ?></h2><ul class="story-menu"><?php foreach(array_slice($section['items'],0,4) as $item): ?><li><strong><?= ghe_h($item['name']) ?></strong> — <?= ghe_price($item['price']) ?><p><?= ghe_h($item['detail']) ?></p></li><?php endforeach; ?></ul><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php').'#'.$section['id']) ?>">See this category →</a></section><?php endforeach; ?>
<?php if(!$menuSections): ?><p>The menu is currently unavailable or being updated. Please call <?= ghe_h($site['phone']) ?> for items and prices.</p><?php endif; ?>
<h2>A note before ordering.</h2><p>If you have a food allergy or a dietary requirement, please speak to our team before you order.</p><h2>See you at Ghé.</h2><p><?= ghe_h($site['address']) ?> · <?= ghe_h($site['hours']) ?></p><a class="button" href="<?= ghe_h(ghe_link('den-ghe.php')) ?>">Plan your visit ↗</a></div></article>
<?php elseif($pageKey==='visit'): ?>
<section class="page-intro wrap"><p class="eyebrow">VISIT GHÉ / DA LAT</p><h1>Save the address.<br><em>Make time to stop by.</em></h1><p class="lead">Find us at <?= ghe_h($site['address']) ?>. Open <?= ghe_h($site['hours']) ?>.</p></section>
<section class="wrap visit-grid section"><div class="address-card"><p class="eyebrow">GHÉ · DA LAT CAFÉ</p><h2><?= ghe_h($site['street']) ?></h2><address><?= ghe_h($site['city'].', '.$site['region']) ?>, Vietnam</address><hr><p class="eyebrow">CONTACT US</p><a class="phone" href="tel:<?= ghe_h($site['telephone']) ?>"><?= ghe_h($site['telephone']) ?></a><p class="eyebrow">OPENING HOURS</p><p class="opening-hours"><?= ghe_h($site['hours']) ?></p><p><?= ghe_h($site['hours_note']) ?></p><div class="actions"><a class="button" href="<?= ghe_h($site['directions']) ?>" target="_blank" rel="noopener noreferrer">Get directions ↗</a><a class="text-link" href="<?= ghe_h($site['maps']) ?>" target="_blank" rel="noopener noreferrer">Google Maps profile ↗</a></div></div><div class="visit-poster"><span class="eyebrow">YOUR NEXT COFFEE STOP</span><span class="poster-flower" aria-hidden="true">✳</span><span class="poster-address" aria-hidden="true">ghé</span><span><?= ghe_h($site['street']) ?></span><p>See you in <em>Da Lat.</em></p></div></section>
<section class="wrap section before-visit"><div><p class="eyebrow">BEFORE YOU ARRIVE</p><h2>A seat for<br>your kind of day.</h2></div><div class="prose"><?php ghe_english_facilities(); ghe_paragraphs($site['visit_note']); ?><p>Contact us at <?= ghe_h($site['telephone']) ?> if you have specific questions.</p><a class="text-link" href="<?= ghe_h($site['maps']) ?>" target="_blank" rel="noopener noreferrer">Guest photos & reviews on Google Maps ↗</a></div></section>
<section class="wrap section faq"><p class="eyebrow">GOOD TO KNOW</p><h2>Before your visit.</h2><?php foreach(ghe_faqs() as $faq): ?><details><summary><?= ghe_h($faq[0]) ?></summary><p><?= ghe_h($faq[1]) ?></p></details><?php endforeach; ?></section>
<?php endif; ?>
<?php require __DIR__.'/site/footer.php'; ?>
