<?php
// Live admin verification, without config.php's automatic shift-close writes.
require __DIR__.'/site/admin-auth.php';
require_once __DIR__.'/site/expense-report.php';
date_default_timezone_set(getenv('POS_TIMEZONE') ?: 'Asia/Ho_Chi_Minh');
$error=''; $report=null;
try { $selectedMonth=expenseReportMonth($_GET['month']??date('Y-m')); }
catch(InvalidArgumentException $exception) {
    http_response_code(400); $error=$exception->getMessage(); $selectedMonth=expenseReportMonth(date('Y-m'));
}
if($error==='') {
    try { $report=expenseReportRead($websiteDb,$selectedMonth); }
    catch(Throwable $exception) { error_log('Expense report: '.$exception->getMessage()); http_response_code(503); $error='Chưa tải được báo cáo tiền chi. Vui lòng thử lại sau; không có dữ liệu nào bị thay đổi.'; }
}
function er_h($value): string { return htmlspecialchars((string)$value,ENT_QUOTES | ENT_SUBSTITUTE,'UTF-8'); }
$month=$selectedMonth->format('Y-m');
$mismatch=$report?count(array_filter($report['days'],function($day){return $day['amount']!==$day['detail_total'];})):0;
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="favicon.svg"><title>Báo cáo tiền chi tháng <?= er_h($selectedMonth->format('m/Y')) ?> — GHÉ</title></head><body>
<?php require __DIR__.'/menu.php'; ?>
<style>
.expense-report{max-width:1200px;margin:auto}.expense-report .stats-grid{margin-bottom:18px}.expense-report .alert{margin-bottom:14px}.expense-report .filters{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.expense-report .filters input{width:auto;min-height:38px}.expense-report .filters .btn{min-height:38px}.expense-report .tbl .amount{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.expense-report .tbl td{vertical-align:top}.expense-report .date{white-space:nowrap}.expense-report .detail{min-width:230px;overflow-wrap:anywhere}.expense-report summary{cursor:pointer;padding:4px 0}.expense-lines{list-style:none;margin-top:8px}.expense-lines li{display:flex;justify-content:space-between;gap:18px;padding:7px 0;border-bottom:1px dashed var(--s200)}.expense-lines .note{white-space:pre-wrap;overflow-wrap:anywhere;min-width:0}.expense-lines .amount{flex-shrink:0}.expense-report tfoot{font-weight:700;background:var(--s50)}.expense-report .pending{margin-top:18px}.expense-report .pending>summary{font-weight:600}.expense-report .pending .tbl-wrap{margin-top:14px}.expense-report .reconcile{margin-top:8px;color:var(--warn);font-size:12px}.expense-report .footnote{margin:14px 0;color:var(--s500);font-size:12px}@media print{.expense-report{max-width:none;padding:0}.expense-report .tbl-wrap{overflow:visible}.expense-report tr{break-inside:avoid}.expense-report details>ul,.expense-report details>.tbl-wrap{display:block!important}.expense-report .card{box-shadow:none}}
</style>
<style>
.expense-report .stats-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.expense-report .stat-value{overflow-wrap:anywhere}
@media(max-width:640px){.expense-report .stats-grid{grid-template-columns:1fr}.expense-report .tbl,.expense-report .tbl tbody,.expense-report .tbl tfoot{display:block;width:100%}.expense-report .tbl caption{display:block;text-align:left}.expense-report .tbl thead{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.expense-report .tbl tbody tr{display:grid;grid-template-columns:minmax(0,1fr) auto;border-bottom:1px solid var(--s200)}.expense-report .tbl .date{grid-column:1;grid-row:1}.expense-report .tbl td.amount{grid-column:2;grid-row:1}.expense-report .tbl .detail{grid-column:1/-1;grid-row:2;min-width:0}.expense-report .tbl td{border:0}.expense-report .tbl tfoot tr{display:flex;align-items:center;justify-content:space-between}.expense-report .tbl tfoot th{min-width:0}.expense-report .tbl tfoot td{flex-shrink:0}.expense-report .pending .tbl-wrap{width:100%}.expense-lines li{flex-wrap:wrap}.expense-lines .amount{margin-left:auto}}
</style>
<main class="page-content expense-report">
<header class="page-hdr"><div class="page-hdr-left"><h1>Báo cáo tiền chi theo tháng</h1><p>Tháng <?= er_h($selectedMonth->format('m/Y')) ?> · Chỉ dành cho admin</p></div><a href="cashbook_history.php" class="btn btn-secondary no-print">Lịch sử chốt ca</a></header>
<form method="get" class="card filters no-print"><div><label class="form-label" for="expense-month">Tháng báo cáo</label><input class="form-input" type="month" id="expense-month" name="month" value="<?= er_h($month) ?>" min="1000-01" max="9999-12" required></div><button class="btn btn-primary">Xem báo cáo</button><a class="btn btn-secondary" href="expense_report.php">Tháng hiện tại</a><?php if($report): ?><button class="btn btn-secondary" type="button" onclick="document.querySelectorAll('.expense-report details').forEach(d=>d.open=true);window.print()">In báo cáo</button><?php endif; ?></form>
<p class="footnote">Tổng tiền chi lấy từ số đã lưu trong lịch sử chốt ca, theo ngày của ca (không theo ngày nhập). Không bao gồm nộp doanh thu, tiền đầu ca hoặc tiền chi của ca chưa chốt / đã mở lại.</p>
<?php if($error!==''): ?><div class="alert alert-err" role="alert"><?= er_h($error) ?></div><?php else: ?>
<section class="stats-grid" aria-label="Tổng hợp tháng"><div class="stat-card"><div class="stat-label">Tổng tiền chi đã chốt</div><div class="stat-value c-red money" id="expense-total"><?= expenseReportMoney($report['total']) ?></div></div><div class="stat-card"><div class="stat-label">Số ngày đã chốt</div><div class="stat-value" id="expense-days"><?= count($report['days']) ?></div></div><div class="stat-card"><div class="stat-label">Khoản chi có chi tiết</div><div class="stat-value" id="expense-count"><?= $report['item_count'] ?></div><div class="stat-sub">Trong các ngày đã chốt</div></div></section>
<?php if($mismatch): ?><div class="alert alert-warn" role="status">Có <?= $mismatch ?> ngày có tổng chi tiết khác số đã chốt. Báo cáo vẫn dùng số trong lịch sử; xem cảnh báo ở từng ngày để đối chiếu.</div><?php endif; ?>
<div class="tbl-wrap"><table class="tbl"><caption class="section-title" style="text-align:left;padding:14px">Tiền chi theo ngày — <?= er_h($selectedMonth->format('m/Y')) ?></caption><thead><tr><th scope="col">Ngày chốt ca</th><th scope="col">Khoản chi</th><th scope="col" class="amount">Tiền chi đã chốt</th></tr></thead><tbody>
<?php if(!$report['days']): ?><tr><td colspan="3"><div class="empty-state">Chưa có ca đã chốt trong tháng này.</div></td></tr><?php endif; ?>
<?php foreach($report['days'] as $date=>$day): ?><tr data-expense-day="<?= er_h($date) ?>"><th scope="row" class="date" style="padding:14px;text-align:left"><a class="c-blue" href="cashbook.php?date=<?= er_h($date) ?>"><?= er_h((new DateTimeImmutable($date))->format('d/m/Y')) ?></a></th><td class="detail">
<?php if($day['items']): ?><details><summary><?= count($day['items']) ?> khoản chi · Xem nội dung</summary><ul class="expense-lines"><?php foreach($day['items'] as $item): ?><li><span class="note"><?= er_h(trim($item['note']??'')!==''?$item['note']:'Không có ghi chú') ?> <small class="text-muted">#<?= (int)$item['id'] ?></small></span><span class="amount"><?= expenseReportMoney($item['cents']) ?></span></li><?php endforeach; ?></ul></details><?php else: ?><span class="text-muted">Không có dòng chi tiết.</span><?php endif; ?>
<?php if($day['amount']!==$day['detail_total']): ?><p class="reconcile">Tổng chi tiết: <?= expenseReportMoney($day['detail_total']) ?>. Chênh lệch (đã chốt − chi tiết): <?= expenseReportMoney($day['amount']-$day['detail_total']) ?>.</p><?php endif; ?></td><td class="amount fw-700 c-red"><?= expenseReportMoney($day['amount']) ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr><th scope="row" colspan="2" style="padding:14px;text-align:left">Tổng tháng <?= er_h($selectedMonth->format('m/Y')) ?></th><td class="amount"><?= expenseReportMoney($report['total']) ?></td></tr></tfoot></table></div>
<?php if($report['pending']): ?><details class="card pending"><summary>Chưa tính vào tổng: <?= count($report['pending']) ?> khoản chi, <?= expenseReportMoney($report['pending_total']) ?></summary><p class="footnote">Các ngày này chưa có bản chốt trong lịch sử (chưa chốt hoặc đã mở lại ca). Số liệu có thể còn thay đổi.</p><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Ngày</th><th>Nội dung</th><th class="amount">Số tiền</th></tr></thead><tbody><?php foreach($report['pending'] as $item): ?><tr><td class="date"><a class="c-blue" href="cashbook.php?date=<?= er_h($item['expense_date']) ?>"><?= er_h((new DateTimeImmutable($item['expense_date']))->format('d/m/Y')) ?></a></td><td class="detail"><?= er_h(trim($item['note']??'')!==''?$item['note']:'Không có ghi chú') ?></td><td class="amount"><?= expenseReportMoney($item['cents']) ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
<?php endif; ?>
</main></body></html>
