<?php
// Live admin verification, without config.php's automatic shift-close writes.
require __DIR__.'/site/admin-auth.php';
require_once __DIR__.'/site/expense-report.php';
date_default_timezone_set(getenv('POS_TIMEZONE') ?: 'Asia/Ho_Chi_Minh');
$error=''; $report=null;
try { $selectedMonth=expenseReportMonth($_GET['month']??date('Y-m')); }
catch(InvalidArgumentException $exception) {
    http_response_code(400); $error=$exception->getMessage(); $selectedMonth=expenseReportMonth(date('Y-m'));
}
if($error==='') {
    try { $report=expenseReportRead($websiteDb,$selectedMonth); }
    catch(Throwable $exception) { error_log('Expense report: '.$exception->getMessage()); http_response_code(503); $error='Chưa tải được báo cáo tiền chi. Vui lòng thử lại sau; không có dữ liệu nào bị thay đổi.'; }
}
function er_h($value): string { return htmlspecialchars((string)$value,ENT_QUOTES | ENT_SUBSTITUTE,'UTF-8'); }
$month=$selectedMonth->format('Y-m');
$mismatch=$report?count(array_filter($report['days'],function($day){return $day['has_closed_shift'] && $day['cash_amount']!==$day['cash_detail_total'];})):0;
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="favicon.svg"><title>Báo cáo tiền chi tháng <?= er_h($selectedMonth->format('m/Y')) ?> — GHÉ</title></head><body>
<?php require __DIR__.'/menu.php'; ?>
<style>
.expense-report{max-width:1280px;margin:auto}.expense-report .stats-grid{margin-bottom:18px}.expense-report .alert{margin-bottom:14px}.expense-report .filters{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.expense-report .filters input{width:auto;min-height:38px}.expense-report .filters .btn{min-height:38px}.expense-report .tbl{min-width:900px}.expense-report .tbl .amount{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.expense-report .tbl td{vertical-align:top}.expense-report .date{white-space:nowrap}.expense-report .detail{min-width:330px;overflow-wrap:anywhere}.expense-report summary{cursor:pointer;padding:4px 0}.expense-group+.expense-group{margin-top:10px}.expense-group-title{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--s500)}.expense-lines{list-style:none;margin-top:5px}.expense-lines li{display:flex;justify-content:space-between;gap:18px;padding:7px 0;border-bottom:1px dashed var(--s200)}.expense-lines .note{white-space:pre-wrap;overflow-wrap:anywhere;min-width:0}.expense-lines .amount{flex-shrink:0}.expense-report tfoot{font-weight:700;background:var(--s50)}.expense-report .pending{margin-top:18px}.expense-report .pending>summary{font-weight:600}.expense-report .pending .tbl-wrap{margin-top:14px}.expense-report .reconcile{margin-top:8px;color:var(--warn);font-size:12px}.expense-report .footnote{margin:14px 0;color:var(--s500);font-size:12px}@media print{.expense-report{max-width:none;padding:0}.expense-report .tbl{min-width:0}.expense-report .tbl-wrap{overflow:visible}.expense-report tr{break-inside:avoid}.expense-report details>ul,.expense-report details>.tbl-wrap{display:block!important}.expense-report .card{box-shadow:none}}
</style>
<style>
.expense-report .stats-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.expense-report .stat-value{overflow-wrap:anywhere}
@media(max-width:800px){.expense-report .stats-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.expense-lines li{flex-wrap:wrap}.expense-lines .amount{margin-left:auto}}@media(max-width:440px){.expense-report .stats-grid{grid-template-columns:1fr}}
</style>
<main class="page-content expense-report">
<header class="page-hdr"><div class="page-hdr-left"><h1>Báo cáo tiền chi theo tháng</h1><p>Tháng <?= er_h($selectedMonth->format('m/Y')) ?> · Chỉ dành cho admin</p></div><a href="cashbook_history.php" class="btn btn-secondary no-print">Lịch sử chốt ca</a></header>
<form method="get" class="card filters no-print"><div><label class="form-label" for="expense-month">Tháng báo cáo</label><input class="form-input" type="month" id="expense-month" name="month" value="<?= er_h($month) ?>" min="1000-01" max="9999-12" required></div><button class="btn btn-primary">Xem báo cáo</button><a class="btn btn-secondary" href="expense_report.php">Tháng hiện tại</a><?php if($report): ?><button class="btn btn-secondary" type="button" onclick="document.querySelectorAll('.expense-report details').forEach(d=>d.open=true);window.print()">In báo cáo</button><?php endif; ?></form>
<p class="footnote">Tổng chung = tiền chi tại quầy đã lưu khi chốt ca + mọi khoản mua hàng outsource theo ngày mua. Không bao gồm nộp doanh thu, tiền đầu ca hoặc tiền chi tại quầy của ca chưa chốt / đã mở lại.</p>
<?php if($error!==''): ?><div class="alert alert-err" role="alert"><?= er_h($error) ?></div><?php else: ?>
<section class="stats-grid" aria-label="Tổng hợp tháng"><div class="stat-card"><div class="stat-label">Tổng tiền chi</div><div class="stat-value c-red money" id="expense-total"><?= expenseReportMoney($report['total']) ?></div><div class="stat-sub">Chi tại quầy + mua hàng</div></div><div class="stat-card"><div class="stat-label">Chi tại quầy đã chốt</div><div class="stat-value c-orange money"><?= expenseReportMoney($report['cash_total']) ?></div><div class="stat-sub"><?= $report['item_count'] ?> khoản có chi tiết</div></div><div class="stat-card"><div class="stat-label">Mua hàng outsource</div><div class="stat-value c-purple money"><?= expenseReportMoney($report['purchase_total']) ?></div><div class="stat-sub"><?= $report['purchase_count'] ?> khoản mua</div></div><div class="stat-card"><div class="stat-label">Số ngày hiển thị</div><div class="stat-value" id="expense-days"><?= count($report['days']) ?></div></div></section>
<?php if($mismatch): ?><div class="alert alert-warn" role="status">Có <?= $mismatch ?> ngày có tổng chi tiết khác số đã chốt. Báo cáo vẫn dùng số trong lịch sử; xem cảnh báo ở từng ngày để đối chiếu.</div><?php endif; ?>
<div class="tbl-wrap"><table class="tbl"><caption class="section-title" style="text-align:left;padding:14px">Tiền chi theo ngày — <?= er_h($selectedMonth->format('m/Y')) ?></caption><thead><tr><th scope="col">Ngày</th><th scope="col">Chi tiết</th><th scope="col" class="amount">Chi tại quầy</th><th scope="col" class="amount">Mua hàng</th><th scope="col" class="amount">Tổng cộng</th></tr></thead><tbody>
<?php if(!$report['days']): ?><tr><td colspan="5"><div class="empty-state">Chưa có khoản chi trong tháng này.</div></td></tr><?php endif; ?>
<?php foreach($report['days'] as $date=>$day): ?><tr data-expense-day="<?= er_h($date) ?>"><th scope="row" class="date" style="padding:14px;text-align:left"><a class="c-blue" href="cashbook.php?date=<?= er_h($date) ?>"><?= er_h((new DateTimeImmutable($date))->format('d/m/Y')) ?></a></th><td class="detail">
<?php if($day['has_closed_shift']): ?><div class="expense-group"><div class="expense-group-title">Chi tại quầy</div><?php if($day['cash_items']): ?><details><summary><?= count($day['cash_items']) ?> khoản · Xem nội dung</summary><ul class="expense-lines"><?php foreach($day['cash_items'] as $item): ?><li><span class="note"><?= er_h(trim($item['note']??'')!==''?$item['note']:'Không có ghi chú') ?> <small class="text-muted">#<?= (int)$item['id'] ?></small></span><span class="amount"><?= expenseReportMoney($item['cents']) ?></span></li><?php endforeach; ?></ul></details><?php else: ?><span class="text-muted">Không có dòng chi tiết.</span><?php endif; ?></div><?php endif; ?>
<?php if($day['purchase_items']): ?><div class="expense-group"><div class="expense-group-title">Mua hàng outsource</div><details><summary><?= count($day['purchase_items']) ?> khoản · Xem nội dung</summary><ul class="expense-lines"><?php foreach($day['purchase_items'] as $item): ?><li><span class="note"><strong><?= er_h($item['item_name']) ?></strong> · <?= er_h(rtrim(rtrim((string)$item['quantity'],'0'),'.')) ?> <?= er_h($item['unit']) ?><?= trim((string)$item['supplier'])!==''?' · '.er_h($item['supplier']):'' ?> <small class="text-muted">· <?= er_h($item['username']) ?> · #<?= (int)$item['id'] ?></small><?php if(trim((string)$item['note'])!==''): ?><br><small><?= er_h($item['note']) ?></small><?php endif; ?></span><span class="amount"><?= expenseReportMoney($item['cents']) ?></span></li><?php endforeach; ?></ul></details></div><?php endif; ?>
<?php if($day['has_closed_shift'] && $day['cash_amount']!==$day['cash_detail_total']): ?><p class="reconcile">Chi tiết tại quầy: <?= expenseReportMoney($day['cash_detail_total']) ?>. Chênh lệch (đã chốt − chi tiết): <?= expenseReportMoney($day['cash_amount']-$day['cash_detail_total']) ?>.</p><?php endif; ?></td><td class="amount"><?= $day['has_closed_shift']?expenseReportMoney($day['cash_amount']):'—' ?></td><td class="amount c-purple"><?= expenseReportMoney($day['purchase_total']) ?></td><td class="amount fw-700 c-red"><?= expenseReportMoney($day['amount']) ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr><th scope="row" colspan="2" style="padding:14px;text-align:left">Tổng tháng <?= er_h($selectedMonth->format('m/Y')) ?></th><td class="amount"><?= expenseReportMoney($report['cash_total']) ?></td><td class="amount"><?= expenseReportMoney($report['purchase_total']) ?></td><td class="amount"><?= expenseReportMoney($report['total']) ?></td></tr></tfoot></table></div>
<?php if($report['pending']): ?><details class="card pending"><summary>Chưa tính vào tổng: <?= count($report['pending']) ?> khoản chi, <?= expenseReportMoney($report['pending_total']) ?></summary><p class="footnote">Các ngày này chưa có bản chốt trong lịch sử (chưa chốt hoặc đã mở lại ca). Số liệu có thể còn thay đổi.</p><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Ngày</th><th>Nội dung</th><th class="amount">Số tiền</th></tr></thead><tbody><?php foreach($report['pending'] as $item): ?><tr><td class="date"><a class="c-blue" href="cashbook.php?date=<?= er_h($item['expense_date']) ?>"><?= er_h((new DateTimeImmutable($item['expense_date']))->format('d/m/Y')) ?></a></td><td class="detail"><?= er_h(trim($item['note']??'')!==''?$item['note']:'Không có ghi chú') ?></td><td class="amount"><?= expenseReportMoney($item['cents']) ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
<?php endif; ?>
</main></body></html>
