<?php $pageKey='home'; require __DIR__.'/site/header.php'; ?>
<section class="hero wrap">
<div class="hero-copy"><p class="eyebrow">GHÉ · CÀ PHÊ ĐÀ LẠT</p><h1><?= nl2br(ghe_h($site['home_title'])) ?></h1><p><?= ghe_h($site['home_intro']) ?></p><p class="opening-hours"><?= ghe_h($site['hours']) ?></p><div class="actions"><a class="button" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>">Xem thực đơn ↗</a><a class="text-link" href="<?= ghe_h(ghe_link('den-ghe.php')) ?>">Đường đến Ghé →</a></div></div>
<?php if(!empty($content['media'][$site['hero_image']])): ?><div class="hero-photo"><?php ghe_photo($site['hero_image'],'',true); ?></div>
<?php else: ?><div class="hero-art" aria-hidden="true"><div class="art-note">ĐÀ LẠT, MỘT NGÀY BẠN GHÉ.</div><div class="art-word">ghé</div><div class="steam steam-one"></div><div class="steam steam-two"></div><div class="saucer"></div><div class="cup"><div class="coffee-surface"></div><span>ghé</span></div><span class="art-flower">✳</span><div class="art-caption">cà phê & những cuộc hẹn</div></div><?php endif; ?>
</section>
<div class="ribbon"><div class="wrap"><span><?= ghe_h($site['hours']) ?></span><span aria-hidden="true">✳</span><span><?= ghe_h($site['street']) ?></span></div></div>
<section class="section wrap intro-grid"><p class="eyebrow">01 / CHÀO BẠN, GHÉ ĐÂY</p><div><h2><?= ghe_h($site['about_title']) ?></h2><p><?= ghe_h(ghe_facilities_sentence()) ?></p><?php ghe_facilities(); ?><a class="text-link" href="<?= ghe_h(ghe_link('gioi-thieu.php')) ?>">Làm quen với Ghé →</a></div></section>
<?php ghe_gallery(); $featured=ghe_featured_items(); if($featured): ?>
<section class="section menu-preview"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">02 / HÔM NAY, BẠN UỐNG GÌ?</p><h2>Mỗi cuộc hẹn,<br>một vị riêng.</h2></div><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>">Xem tất cả món →</a></div><div class="drink-grid">
<?php foreach($featured as $index=>$drink): ?><article class="drink-card"><?php if(!empty($content['media'][$drink['image']])): ghe_photo($drink['image'],'drink-photo'); else: ?><div class="drink-art <?= ['coffee','citrus','matcha'][$index%3] ?>" aria-hidden="true"><div class="glass"><span>ghé</span></div><small>MINH HỌA HƯƠNG VỊ</small></div><?php endif; ?><div class="drink-title"><h3><?= ghe_h($drink['name']) ?></h3><span><?= ghe_price($drink['price']) ?></span></div><p><?= ghe_h($drink['detail']) ?></p></article><?php endforeach; ?>
</div></div></section><?php endif; ?>
<section class="section wrap story-teaser"><div class="editorial-number" aria-hidden="true">ghé<br><em>uống gì?</em></div><div><p class="eyebrow">03 / MỘT CHÚT GỢI Ý</p><h2>Chọn món cho<br>cuộc hẹn của bạn.</h2><p>Khám phá các nhóm món đang phục vụ tại Ghé và chọn theo sở thích của mình.</p><a class="text-link" href="<?= ghe_h(ghe_link('ghe-uong-gi.php')) ?>">Đi một vòng thực đơn →</a></div></section>
<?php if($publishedPosts): ?><section class="wrap section"><p class="eyebrow">CHUYỆN Ở GHÉ</p><div class="post-grid"><?php foreach(array_slice(array_reverse($publishedPosts,true),0,3,true) as $post): ?><article><h2><a href="<?= ghe_h(ghe_link('bai-viet.php?slug='.rawurlencode($post['slug']))) ?>"><?= ghe_h($post['title']) ?></a></h2><p><?= ghe_h($post['excerpt']) ?></p></article><?php endforeach; ?></div><a class="text-link" href="<?= ghe_h(ghe_link('chuyen-o-ghe.php')) ?>">Xem các bài viết →</a></section><?php endif; ?>
<section class="section wrap location-strip"><p class="eyebrow">LƯU LẠI CHO LẦN GHÉ TỚI</p><h2><?= ghe_h($site['address']) ?></h2><p><?= ghe_h($site['hours']) ?></p><a class="button outline" href="<?= ghe_h($site['maps']) ?>" target="_blank" rel="noopener noreferrer">Xem Ghé trên bản đồ ↗</a></section>
<?php require __DIR__.'/site/footer.php'; ?>
