<?php
require __DIR__ . '/site/admin-auth.php';
require_once __DIR__ . '/site/admin-actions.php';
$catalog = ghe_catalog_rows($websiteDb);
$tab = (string)($_GET['tab'] ?? 'content');
if (!in_array($tab,['content','photos','menu','posts'],true)) $tab='content';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_require(is_string($_POST['csrf_token'] ?? null) ? $_POST['csrf_token'] : '');
    $productSave = ($_POST['action'] ?? '') === 'product';
    $jsonResponse = $productSave && strpos($_SERVER['HTTP_ACCEPT'] ?? '', 'application/json') !== false;
    try { $result=['success',ghe_admin_action($_POST,$_FILES,$catalog)]; }
    catch (Throwable $e) { $result=['error',$e instanceof mysqli_sql_exception ? 'Không đọc được POS. Vui lòng thử lại.' : $e->getMessage()]; }
    if ($jsonResponse) {
        header('Content-Type: application/json; charset=utf-8');
        http_response_code($result[0] === 'success' ? 200 : 400);
        // Return the revision of this write, never a newer revision from another editor.
        echo json_encode(['ok'=>$result[0]==='success','message'=>$result[1],
            'revision'=>$result[0]==='success' ? (int)$_POST['revision']+1 : null], JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
        exit;
    }
    $productId = $productSave ? (int)($_POST['id'] ?? 0) : 0;
    if ($productId > 0) $result[2]=$productId;
    $_SESSION['website_notice']=$result;
    header('Location: website-admin.php?tab=' . $tab . ($productId > 0 ? '#product-'.$productId : '')); exit;
}
$state=ghe_state_read(); $draft=$state['draft']; $settings=$draft['settings'];
$notice=$_SESSION['website_notice'] ?? null; unset($_SESSION['website_notice']);
function wa_h($value): string {return htmlspecialchars((string)$value,ENT_QUOTES | ENT_SUBSTITUTE,'UTF-8');}
function wa_form(string $action): void {global $state; echo csrf_field() . '<input type="hidden" name="revision" value="' . (int)$state['revision'] . '"><input type="hidden" name="action" value="'.wa_h($action).'">';}
function wa_input(string $name,string $label,$value,string $type='text',int $max=200): void {echo '<label>'.wa_h($label).'<input name="'.wa_h($name).'" type="'.wa_h($type).'" value="'.wa_h($value).'" maxlength="'.$max.'" required></label>';}
function wa_area(string $name,string $label,$value,int $max,int $rows=4): void {echo '<label>'.wa_h($label).'<textarea name="'.wa_h($name).'" maxlength="'.$max.'" rows="'.$rows.'" required>'.wa_h($value).'</textarea></label>';}
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Quản trị website — Ghé</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="assets/website-admin.css?v=2"><script src="assets/website-admin.js?v=1" defer></script></head><body>
<?php include __DIR__ . '/menu.php'; ?>
<main class="wa"><header class="wa-heading"><div><h1>Website của Ghé</h1><p>Nội dung, ảnh và thực đơn dành cho khách.</p></div><a class="wa-button secondary" href="website-preview.php" target="_blank" rel="noopener">Xem trước bản nháp ↗</a></header>
<?php if ($notice): ?><p class="wa-notice <?= wa_h($notice[0]) ?>" role="status"><?= wa_h($notice[1]) ?></p><?php endif; ?>
<section class="wa-publish"><div><strong><?= $state['draft'] == $state['published'] ? 'Bản nháp đang khớp nội dung công khai' : 'Có thay đổi chưa xuất bản' ?></strong><p>Xuất bản áp dụng toàn bộ nội dung, ảnh, bài viết và cài đặt menu đã lưu nháp. Tên và giá món luôn lấy trực tiếp từ POS.</p></div><form method="post"><?php wa_form('publish'); ?><button class="wa-button" type="submit">Xuất bản website</button></form><form method="post"><?php wa_form('reset_draft'); ?><button class="wa-button secondary" type="submit" onclick="return confirm('Khôi phục bản nháp về nội dung đang công khai?')">Khôi phục bản nháp</button></form></section>
<nav class="wa-tabs" aria-label="Quản trị website"><?php foreach (['content'=>'Nội dung & thông tin','photos'=>'Thư viện ảnh','menu'=>'Menu từ POS','posts'=>'Bài viết'] as $key=>$label): ?><a href="website-admin.php?tab=<?= $key ?>"<?= $tab===$key?' aria-current="page"':'' ?>><?= $label ?></a><?php endforeach; ?></nav>
<?php if ($tab==='content'): ?>
<form method="post" class="wa-panel"><?php wa_form('settings'); ?><h2>Thông tin quán</h2><div class="wa-grid">
<?php wa_input('street','Số nhà, đường',$settings['street'],'text',180); wa_input('city','Thành phố / khu vực',$settings['city'],'text',100); wa_input('region','Tỉnh',$settings['region'],'text',100); wa_input('phone','Số điện thoại',$settings['phone'],'tel',30); wa_input('maps','Liên kết Google Maps',$settings['maps'],'url',1000); ?>
</div><h2>Giờ hoạt động hằng ngày</h2><div class="wa-grid"><?php wa_input('opens','Giờ mở cửa',$settings['opens'],'time',5); wa_input('closes','Giờ đóng cửa',$settings['closes'],'time',5); ?><label>Ghi chú giờ hoạt động<input name="hours_note" maxlength="250" value="<?= wa_h($settings['hours_note']) ?>"></label></div>
<h2>Không gian & tiện ích</h2><p>Chỉ thông tin đã xác nhận mới xuất hiện trên website và dữ liệu tìm kiếm.</p><div class="wa-grid"><?php foreach (ghe_facility_labels() as $key=>$label): ?><label><?= wa_h($label) ?><select name="facilities[<?= $key ?>]"><?php foreach (['unknown'=>'Chưa xác nhận','yes'=>'Có','no'=>'Không'] as $value=>$text): ?><option value="<?= $value ?>"<?= ($draft['facilities'][$key]??'unknown')===$value?' selected':'' ?>><?= $text ?></option><?php endforeach; ?></select><input name="facility_details[<?= $key ?>]" maxlength="200" aria-label="Chi tiết <?= wa_h($label) ?>" placeholder="Chi tiết bổ sung (không bắt buộc)" value="<?= wa_h($draft['facility_details'][$key]??'') ?>"></label><?php endforeach; ?></div>
<h2>Nội dung giới thiệu</h2><?php wa_area('home_title','Tiêu đề trang chủ (mỗi dòng là một dòng tiêu đề)',$settings['home_title'],160,3); wa_area('home_intro','Mô tả đầu trang chủ',$settings['home_intro'],1000); wa_input('about_title','Tiêu đề giới thiệu',$settings['about_title'],'text',180); wa_area('about_body','Bài giới thiệu (cách đoạn bằng một dòng trống)',$settings['about_body'],15000,9); wa_area('menu_intro','Lời giới thiệu thực đơn',$settings['menu_intro'],1500); wa_area('visit_note','Lưu ý trước khi đến quán',$settings['visit_note'],1500); ?><button class="wa-button">Lưu bản nháp</button></form>
<details class="wa-panel"><summary>Nội dung tiếng Anh dành cho khách</summary><p>Giờ mở cửa, địa chỉ, số điện thoại, ảnh, giá và trạng thái món dùng chung với bản tiếng Việt. Phần chữ tiếng Anh được quản lý riêng; thay đổi cần xuất bản. Để trống để dùng nội dung tiếng Anh mặc định. Bài viết hiện giữ tiếng Việt.</p><a class="wa-button secondary" href="website-preview.php?page=en.php" target="_blank" rel="noopener">Xem trước tiếng Anh ↗</a><form method="post"><?php wa_form('english_settings'); $englishValues=ghe_english_defaults(); foreach($englishValues as $key=>$fallback) if(trim($draft['settings_en'][$key]??'')!=='')$englishValues[$key]=$draft['settings_en'][$key]; ?>
<?php foreach(['home_title'=>['Tiêu đề trang chủ',160,3],'home_intro'=>['Giới thiệu trang chủ',1000,4],'about_title'=>['Tiêu đề giới thiệu',180,2],'about_body'=>['Bài giới thiệu',15000,8],'menu_intro'=>['Lời giới thiệu thực đơn',1500,4],'visit_note'=>['Lưu ý trước khi đến',1500,4],'hours_note'=>['Ghi chú giờ mở cửa',250,2]] as $key=>$field): ?><label><?= wa_h($field[0]) ?> — English<textarea lang="en" name="<?= wa_h($key) ?>" maxlength="<?= $field[1] ?>" rows="<?= $field[2] ?>"><?= wa_h($englishValues[$key]) ?></textarea></label><?php endforeach; ?>
<h3>Chi tiết tiện ích — English</h3><p>Để trống sẽ dùng bản dịch mặc định cho các chi tiết đã xác nhận ban đầu. Khi đổi thông tin tiện ích tiếng Việt, hãy cập nhật tiếng Anh tương ứng.</p><div class="wa-grid"><?php foreach(ghe_facility_labels() as $key=>$label): ?><label><?= wa_h($label) ?><input lang="en" name="facility_details_en[<?= $key ?>]" maxlength="200" value="<?= wa_h($draft['facility_details_en'][$key]??'') ?>" placeholder="<?= wa_h(ghe_english_facility_details($draft)[$key]) ?>"></label><?php endforeach; ?></div><button class="wa-button">Lưu nội dung tiếng Anh</button></form></details>
<?php elseif ($tab==='photos'): ?>
<form class="wa-panel" method="post" enctype="multipart/form-data"><?php wa_form('upload'); ?><h2>Thêm ảnh thật của quán</h2><p>JPEG, PNG hoặc WebP; tối đa 8 MB và 20 megapixel. Ảnh được tối ưu thành WebP 1600px và ảnh nhỏ 480px, bỏ metadata khi mã hóa lại.</p><label>Chọn ảnh<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><?php wa_input('alt','Mô tả ảnh cho người đọc và công cụ tìm kiếm','','text',200); ?><label>Mô tả ảnh — English<input lang="en" name="alt_en" maxlength="200"></label><label>Chú thích — English<input lang="en" name="caption_en" maxlength="300"></label><label>Chú thích<input name="caption" maxlength="300"></label><label class="wa-check"><input type="checkbox" name="gallery" checked>Hiển thị trong thư viện không gian quán</label><button class="wa-button">Tải ảnh & lưu nháp</button></form>
<?php if (!$draft['media']): ?><p class="wa-panel">Chưa có ảnh. Bạn có thể tải ảnh sau; trang khách hiện dùng minh họa và không hiển thị khung ảnh trống.</p><?php endif; ?>
<div class="wa-photo-grid"><?php foreach ($draft['media'] as $id=>$media): ?><article class="wa-panel"><img class="wa-photo" src="ghe-image.php?id=<?= wa_h($id) ?>&size=thumb&preview=1" alt="<?= wa_h($media['alt']) ?>" loading="lazy"><form method="post"><?php wa_form('media'); ?><input type="hidden" name="id" value="<?= wa_h($id) ?>"><?php wa_input('alt','Mô tả ảnh',$media['alt'],'text',200); ?><label>Mô tả ảnh — English<input lang="en" name="alt_en" maxlength="200" value="<?= wa_h($media['alt_en']??'') ?>"></label><label>Chú thích — English<input lang="en" name="caption_en" maxlength="300" value="<?= wa_h($media['caption_en']??'') ?>"></label><label>Chú thích<input name="caption" maxlength="300" value="<?= wa_h($media['caption']) ?>"></label><label>Thứ tự (số nhỏ trước)<input type="number" name="order" min="0" max="9999" value="<?= (int)$media['order'] ?>"></label><label class="wa-check"><input type="checkbox" name="gallery"<?= $media['gallery']?' checked':'' ?>>Hiển thị trong thư viện</label><label class="wa-check"><input type="checkbox" name="hero"<?= $settings['hero_image']===$id?' checked':'' ?>>Dùng làm ảnh đầu trang chủ</label><button class="wa-button">Lưu ảnh</button></form><form method="post" class="wa-remove"><?php wa_form('remove_media'); ?><input type="hidden" name="id" value="<?= wa_h($id) ?>"><button class="wa-button secondary" onclick="return confirm('Gỡ ảnh khỏi bản nháp và các món đang dùng ảnh này?')">Gỡ khỏi bản nháp</button></form></article><?php endforeach; ?></div>
<?php elseif ($tab==='menu'): ?>
<div class="wa-panel"><h2>Thực đơn kết nối POS</h2><p>Tên và giá đọc từ POS theo mã món, không nhập lại ở đây. Món mới đang bán mặc định được hiển thị. Món ngừng bán trên POS tự ẩn; các thay đổi mô tả, ảnh và công tắc dưới đây cần xuất bản.</p><a href="products.php">Mở quản lý món trong POS →</a></div>
<?php if (!$catalog): ?><p class="wa-panel">POS chưa có món. Thêm món tại mục Thực đơn của POS.</p><?php endif; ?>
<div class="wa-products"><?php foreach ($catalog as $row): $meta=$draft['products'][(string)$row['id']] ?? []; ?><form class="wa-panel" method="post" id="product-<?= (int)$row['id'] ?>" data-inline-save><?php wa_form('product'); ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><h3><?= wa_h($row['name']) ?> <small>#<?= (int)$row['id'] ?></small></h3><p><?= wa_h($row['category_name']) ?> · <?= number_format((int)$row['price'],0,',','.') ?>đ · <?= (int)$row['status']===1?'Đang bán':'Ngừng bán — luôn ẩn trên website' ?></p><label>Mô tả công khai<textarea name="description" rows="3" maxlength="1000"><?= wa_h($meta['description'] ?? '') ?></textarea></label><label>Tên món — English<input lang="en" name="name_en" maxlength="200" value="<?= wa_h($meta['name_en']??'') ?>" placeholder="Để trống để dùng bản dịch có sẵn"></label><label>Mô tả — English<textarea lang="en" name="description_en" rows="3" maxlength="1000" placeholder="Để trống để dùng bản dịch có sẵn nếu có"><?= wa_h($meta['description_en']??'') ?></textarea></label><label>Ảnh món<select name="image"><option value="">Chưa chọn ảnh</option><?php foreach ($draft['media'] as $id=>$image): ?><option value="<?= wa_h($id) ?>"<?= ($meta['image']??'')===$id?' selected':'' ?>><?= wa_h($image['alt']) ?></option><?php endforeach; ?></select></label><label class="wa-check"><input type="checkbox" name="visible"<?= ($meta['visible']??true)?' checked':'' ?>>Hiển thị trên website</label><label class="wa-check"><input type="checkbox" name="featured"<?= ($meta['featured']??false)?' checked':'' ?>>Gợi ý trên trang chủ</label><button class="wa-button">Lưu thông tin món</button><p class="wa-save-status<?= ($notice[2]??0)===(int)$row['id']?' '.wa_h($notice[0]):'' ?>" data-save-status role="status" aria-live="polite"><?= ($notice[2]??0)===(int)$row['id']?wa_h($notice[1]):'' ?></p></form><?php endforeach; ?></div>
<?php else: $edit = is_string($_GET['edit'] ?? null) ? $_GET['edit'] : ''; $article=$draft['posts'][$edit] ?? ['slug'=>'','title'=>'','excerpt'=>'','body'=>'','enabled'=>true]; ?>
<form class="wa-panel" method="post"><?php wa_form('post'); ?><h2><?= $edit?'Sửa bài viết':'Viết bài mới' ?></h2><input type="hidden" name="original_slug" value="<?= wa_h($article['slug']) ?>"><?php wa_input('title','Tiêu đề bài viết',$article['title'],'text',160); ?><label>Đường dẫn (ví dụ: mot-buoi-sang-o-ghe)<input name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="100" value="<?= wa_h($article['slug']) ?>"<?= $article['slug']?' readonly':'' ?> required></label><?php wa_area('excerpt','Mô tả ngắn / mô tả tìm kiếm',$article['excerpt'],320,3); wa_area('body','Nội dung (văn bản thuần, cách đoạn bằng dòng trống)',$article['body'],30000,12); ?><label class="wa-check"><input type="checkbox" name="enabled"<?= $article['enabled']?' checked':'' ?>>Hiển thị khi xuất bản website</label><button class="wa-button">Lưu bài vào bản nháp</button></form>
<?php foreach ($draft['posts'] as $slug=>$entry): ?><article class="wa-panel"><h3><?= wa_h($entry['title']) ?></h3><p><?= $entry['enabled']?'Sẵn sàng xuất bản':'Đang ẩn' ?></p><div class="wa-row"><a href="website-admin.php?tab=posts&edit=<?= rawurlencode($slug) ?>">Chỉnh sửa</a><a href="website-preview.php?page=bai-viet.php&slug=<?= rawurlencode($slug) ?>" target="_blank" rel="noopener">Xem trước ↗</a></div><form class="wa-remove" method="post"><?php wa_form('remove_post'); ?><input type="hidden" name="slug" value="<?= wa_h($slug) ?>"><button class="wa-button secondary" onclick="return confirm('Gỡ bài khỏi bản nháp?')">Gỡ khỏi bản nháp</button></form></article><?php endforeach; ?>
<?php endif; ?>
</main></body></html>
