<?php // Shared homepage: visit details appear only in home-footer.php. ?>
<section class="hero wrap">
<div class="hero-copy"><p class="eyebrow"><?= ghe_t('GHÉ · CÀ PHÊ ĐÀ LẠT','GHÉ · DA LAT CAFÉ') ?></p><h1><?= nl2br(ghe_h($site['home_title'])) ?></h1><p><?= ghe_h(trim($site['home_lead']??'') ?: (ghe_is_english()?ghe_english_defaults()['home_lead']:ghe_content_defaults()['settings']['home_lead'])) ?></p><div class="actions"><a class="button" href="<?= ghe_h(ghe_link('khong-gian.php')) ?>"><?= ghe_t('Khám phá không gian','Explore our spaces') ?> ↗</a><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>"><?= ghe_t('Xem thực đơn','Browse the menu') ?> →</a></div></div>
<?php if(!empty($content['media'][$site['hero_image']])): ?><div class="hero-photo"><?php ghe_photo($site['hero_image'],'',true); ?></div><?php else: ?><div class="home-word-art" aria-hidden="true">ghé<span><?= ghe_t('một chút bình yên.','a little time for you.') ?></span></div><?php endif; ?>
</section>
<div class="home-spaces">
<?php ghe_gallery(false,3,true); ?>
<section class="wrap home-amenities" aria-labelledby="home-amenities-heading"><div><p class="eyebrow"><?= ghe_t('Ở LẠI MỘT CHÚT','SETTLE IN') ?></p><h2 id="home-amenities-heading"><?= ghe_t('Cho nhịp riêng<br> của bạn.','At your<br> own pace.') ?></h2><a class="text-link" href="<?= ghe_h(ghe_link('gioi-thieu.php')) ?>"><?= ghe_t('Một chút về Ghé','A little about Ghé') ?> →</a></div><div><?php if(ghe_is_english())ghe_english_facilities();else ghe_facilities(); ?></div></section>
</div>
<?php $featured=ghe_featured_items(); if($featured): ?>
<section class="section home-drinks wrap"><div class="section-heading"><div><p class="eyebrow"><?= ghe_t('TỪ THỰC ĐƠN CỦA GHÉ','FROM OUR MENU') ?></p><h2><?= ghe_t('Hôm nay, bạn uống gì?','What are you having?') ?></h2></div><a class="text-link" href="<?= ghe_h(ghe_link('thuc-don.php')) ?>"><?= ghe_t('Xem tất cả món','Explore the full menu') ?> →</a></div><div class="drink-grid">
<?php foreach($featured as $drink): ?><article class="drink-card"><?php if(!empty($content['media'][$drink['image']])): ghe_menu_photo($drink,'drink-photo');else: ?><div class="drink-placeholder" aria-hidden="true"><span>ghé</span><small><?= ghe_t('MÓN TẠI QUÁN','ON OUR MENU') ?></small></div><?php endif; ?><div class="drink-title"><h3><?= ghe_h($drink['name']) ?></h3><span><?= ghe_price($drink['price']) ?></span></div><p><?= ghe_h($drink['detail']) ?></p></article><?php endforeach; ?>
</div><a class="home-menu-guide text-link" href="<?= ghe_h(ghe_link('ghe-uong-gi.php')) ?>"><?= ghe_t('Một chút gợi ý để chọn món','A little help choosing your drink') ?> →</a></section>
<?php endif; ?>
<?php if(!ghe_is_english() && $publishedPosts): ?><section class="wrap section home-journal"><div class="section-heading"><div><p class="eyebrow">CHUYỆN Ở GHÉ</p><h2>Vài chuyện nhỏ từ quán.</h2></div><a class="text-link" href="<?= ghe_h(ghe_link('chuyen-o-ghe.php')) ?>">Xem các bài viết →</a></div><div class="post-grid"><?php foreach(array_slice(array_reverse($publishedPosts,true),0,3,true) as $post): ?><article><h3><a href="<?= ghe_h(ghe_link('bai-viet.php?slug='.rawurlencode($post['slug']))) ?>"><?= ghe_h($post['title']) ?></a></h3><p><?= ghe_h($post['excerpt']) ?></p></article><?php endforeach; ?></div></section><?php endif; ?>
