<?php
// English name, matching Vietnamese seed description, English description.
// Prices and sale status are deliberately not duplicated here.
return [
    'Đen'=>['Vietnamese black coffee','Cà phê đen truyền thống','Traditional Vietnamese black coffee.'],
    'Nâu'=>['Vietnamese milk coffee','Cà phê sữa truyền thống','Traditional Vietnamese coffee with milk.'],
    'Bạc xỉu'=>['Bạc xỉu — milky coffee','Êm, thơm sữa','A smooth, milky coffee.'],
    'Espresso'=>['Espresso','Một shot cà phê cô đặc','A concentrated shot of coffee.'],
    'Americano'=>['Americano','Espresso pha cùng nước','Espresso with water.'],
    'Ba chỉ'=>['Three-layer coffee','Cà phê ba tầng','A layered coffee drink.'],
    'Muối'=>['Salt cream coffee','Cà phê kem muối','Coffee topped with salted cream.'],
    'Sữa dừa'=>['Coconut milk coffee','Cà phê sữa dừa','Coffee with coconut milk.'],
    'Coldbrew truyền thống'=>['Classic cold brew','Ủ lạnh dịu nhẹ','Smooth cold-brewed coffee.'],
    'Coldbrew chanh sả'=>['Lime & lemongrass cold brew','Chanh và sả thơm mát','Cold brew with refreshing lime and lemongrass.'],
    'Espresso cam'=>['Orange espresso','Espresso cùng nước cam','Espresso with orange juice.'],
    'Caramel'=>['Caramel coffee','Thơm ngọt caramel','Coffee with sweet caramel flavour.'],
    'Latte'=>['Latte','Espresso và sữa','Espresso with milk.'],
    'Mocha'=>['Mocha','Cà phê, sữa và chocolate','Coffee, milk and chocolate.'],
    'Sữa ô-long rang'=>['Roasted oolong milk tea','Bản nóng kèm trân châu trắng','The hot version comes with white tapioca pearls.'],
    'Ấm áp'=>['Warming tea','Gừng, quế, cam, mật ong','Ginger, cinnamon, orange and honey.'],
    'An thần'=>['Jujube & longan tea','Táo đỏ, kỷ tử, long nhãn, mật ong','Jujube, goji berries, dried longan and honey.'],
    'Thư giãn'=>['Floral tea','Hoa hồng, hoa cúc, hoa lài','Rose, chrysanthemum and jasmine.'],
    'Ổi chanh dây'=>['Guava & passion fruit tea','Trà ổi hồng và chanh dây','Pink guava and passion fruit tea.'],
    'Đào Quận Cam'=>['Peach & orange tea','Trà đào và cam','Tea with peach and orange.'],
    'Ô-long kem trứng'=>['Egg cream oolong tea','Trà ô-long phủ kem trứng','Oolong tea topped with egg cream.'],
    'Matcha latte'=>['Matcha latte','Sữa tươi hoặc sữa yến mạch','With dairy milk or oat milk.'],
    'Matcha sữa dừa'=>['Coconut milk matcha','Matcha cùng sữa dừa','Matcha with coconut milk.'],
    'Matcha sữa kem'=>['Cream-topped matcha','Matcha phủ lớp kem sữa','Matcha topped with milk cream.'],
    'Choco'=>['Chocolate','Chocolate nguyên vị','Classic chocolate.'],
    'Choco muối'=>['Salt cream chocolate','Chocolate phủ kem muối','Chocolate topped with salted cream.'],
    'Choco sữa dừa'=>['Coconut milk chocolate','Chocolate cùng sữa dừa','Chocolate with coconut milk.'],
    'Kombucha trái cây'=>['Fruit kombucha','Chọn vị dâu tây, gừng hoặc xoài','Choose strawberry, ginger or mango.'],
    'Cam'=>['Orange juice','Nước cam','Orange juice.'],
    'Chanh dây'=>['Passion fruit juice','Nước chanh dây','Passion fruit juice.'],
    'Sữa chua hạt'=>['Yogurt with nuts & cereal','Hạt điều, óc chó và ngũ cốc','With cashews, walnuts and cereal.'],
    'Sữa chua trái cây'=>['Fruit yogurt','Chọn chanh dây, việt quất hoặc dâu tằm','Choose passion fruit, blueberry or mulberry.'],
    'Sandwich trứng'=>['Egg sandwich','Sandwich kẹp trứng','A sandwich with an egg filling.'],
    'Mì tôm trứng nước'=>['Instant noodle soup with egg','Mì nước ăn cùng trứng','Noodle soup served with egg.'],
    'Khoai tây chiên'=>['French fries','Giòn nóng','Hot, crispy fries.'],
    'Combo viên chiên'=>['Fried snack platter','Cá, tôm, xúc xích, khoai tây, đậu bắp và dưa leo','Fish and shrimp snacks, sausage, potatoes, okra and cucumber.'],
    'Croissant truyền thống'=>['Classic croissant','Bánh sừng bò nguyên vị','A plain croissant.'],
    'Croissant dừa / choco'=>['Coconut or chocolate croissant','Chọn vị dừa hoặc chocolate','Choose coconut or chocolate.'],
    'Cookie matcha'=>['Matcha cookie','Bánh quy vị matcha','A matcha-flavoured cookie.'],
    'Cookie choco'=>['Chocolate cookie','Bánh quy vị chocolate','A chocolate-flavoured cookie.'],
];
